version: '3.8'

services:
  minio:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - app-network

  mc-init:
    image: minio/mc
    depends_on:
      - minio
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
      until /usr/bin/mc config host add minio http://minio:9000 minioadmin minioadmin; do
        echo 'Waiting for MinIO to be ready...'
        sleep 1
      done;
      /usr/bin/mc mb minio/raw-ingestion-zone || true;
      /usr/bin/mc mb minio/process-zone || true;
      /usr/bin/mc mb minio/access-zone || true;
      /usr/bin/mc mb minio/govern-zone || true;
      /usr/bin/mc mb minio/govern-zone-metadata || true;
      /usr/bin/mc mb minio/govern-zone-security || true;
      echo 'MinIO buckets created successfully'
      exit 0;
      "
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - app-network

  trino:
    image: trinodb/trino:403
    container_name: trino
    ports:
      - "8085:8080"
    volumes:
      - ./config/trino/:/etc/trino/
    depends_on:
      - minio
      - postgres
    networks:
      - app-network

  superset:
    image: apache/superset:2.1.0
    container_name: superset
    ports:
      - "8088:8088"
    depends_on:
      - postgres
      - trino
    environment:
      SUPERSET_SECRET_KEY: "your_secret_key_here"
      SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://postgres:postgres@postgres:5432/postgres"
    volumes:
      - ./config/superset:/app/superset_home
    entrypoint: >
      /bin/sh -c "
      until nc -z postgres 5432; do
        echo 'Waiting for PostgreSQL to be ready...'
        sleep 2
      done;
      pip install --no-cache-dir trino psycopg2-binary;
      superset db upgrade;
      superset fab create-admin --username admin --firstname Admin --lastname User --email admin@example.com --password admin || true;
      superset init;
      superset run -p 8088 --with-threads --reload --debugger
      "
    networks:
      - app-network

  python-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-client
    volumes:
      - ./scripts:/scripts
      - ./data:/data
    depends_on:
      - trino
      - minio
      - postgres
      - superset
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  minio_data:
  postgres_data:
